export const teams = [
  {
    name: "Thunderhawks FC",
    image: "team_assets/zues_logo",
    id: "1",
    attack: 65,
    midfield: 57,
    defense: 47,
    foundingYear: 1960,
    jersey: "#3498db",
    colors: ["blue", "silver"],
    colorCodes: ["#3498db", "#bdc3c7"],
    achievements: [
      "Dominant in the 1980s",
      "Multiple championships",
      "Perennial contender",
    ],
    fanbase: "Storm Legion",
  },
  {
    name: "Phoenix United",
    image: "team_assets/knights_logo",
    id: "2",
    attack: 62,
    midfield: 54,
    defense: 45,
    jersey: "#3498db",
    foundingYear: 1995,
    colors: ["blue", "yellow"],
    colorCodes: ["#3498db", "#f39c12"],
    achievements: [
      "Championship in 2007",
      "Rise from lower divisions",
      "Never-say-die attitude",
    ],
    fanbase: "Phoenix Ultras",
  },
  {
    name: "Serpentara FC",
    image: "team_assets/lions_logo",
    id: "3",
    attack: 61,
    midfield: 59,
    defense: 52,
    foundingYear: 1988,
    jersey: "#8e44ad",
    colors: ["purple", "slate"],
    colorCodes: ["#8e44ad", "#596275"],
    achievements: [
      "League title in third season",
      "Cultural identity connection",
      "Passionate Serpentari fanbase",
    ],
    fanbase: "Serpentari",
  },
  {
    name: "Eagle Crest FC",
    image: "team_assets/eagles_logo",
    id: "4",
    attack: 59,
    midfield: 58,
    defense: 50,
    jersey: "#8b4513",
    foundingYear: 1992,
    colors: ["brown", "green"],
    colorCodes: ["#8b4513", "#008000"],
    achievements: ["Balanced Offense and Defense", "Established in 1992"],
    fanbase: "Harvesters",
  },

  {
    name: "Gallop United",
    image: "team_assets/sunrise_logo",
    id: "5",
    attack: 61,
    midfield: 54,
    defense: 49,
    foundingYear: 2000,
    jersey: "#00ff00",
    colors: ["green", "red"],
    colorCodes: ["#00ff00", "#c92d2d"],
    achievements: [
      "Speed and Precision",
      "Strategic Teamwork",
      "Founded in 2000",
    ],
    fanbase: "Gallop Nation",
  },
  {
    name: "Harvest Harts FC",
    image: "team_assets/hearts_logo",
    id: "6",
    attack: 59,
    midfield: 53,
    defense: 49,
    foundingYear: 1975,
    jersey: "#ffd700",
    colors: ["gold", "black"],
    colorCodes: ["#ffd700", "#000000"],
    achievements: [
      "Consistent Playoff Appearances",
      "Strong Aerial Attack Strategy",
      "Established in 1975",
    ],
    fanbase: "Eagle Squadron",
  },
];
