export const teams = [
  {
    name: "Thunderhawks FC",
    image: "team-a",
    id: "1",
    attack: 95,
    defense: 80,
    foundingYear: 1960,
    colors: ["blue", "silver"],
    colorCodes: ["#3498db", "#bdc3c7"],
    achievements: [
      "Dominant in the 1980s",
      "Multiple championships",
      "Perennial contender",
    ],
    fanbase: "Storm Legion",
  },
  {
    name: "Phoenix United",
    image: "team-b",
    id: "2",
    attack: 80,
    defense: 82,
    foundingYear: 1995,
    colors: ["blue", "yellow"],
    colorCodes: ["#3498db", "#f39c12"],
    achievements: [
      "Championship in 2007",
      "Rise from lower divisions",
      "Never-say-die attitude",
    ],
    fanbase: "Phoenix Ultras",
  },
  {
    name: "Serpentara FC",
    image: "team-c",
    id: "3",
    attack: 90,
    defense: 78,
    foundingYear: 1988,
    colors: ["purple", "slate"],
    colorCodes: ["#8e44ad", "#596275"],
    achievements: [
      "League title in third season",
      "Cultural identity connection",
      "Passionate Serpentari fanbase",
    ],
    fanbase: "Serpentari",
  },
  {
    name: "Harvest Harts FC",
    image: "team-f",
    id: "4",
    attack: 87,
    defense: 84,
    foundingYear: 1992,
    colors: ["brown", "green"],
    colorCodes: ["#8b4513", "#008000"],
    achievements: ["Balanced Offense and Defense", "Established in 1992"],
    fanbase: "Harvesters",
  },

  {
    name: "Gallop United",
    image: "team-e",
    id: "5",
    attack: 92,
    defense: 79,
    foundingYear: 2000,
    colors: ["green", "white"],
    colorCodes: ["#00ff00", "#ffffff"],
    achievements: [
      "Speed and Precision",
      "Strategic Teamwork",
      "Founded in 2000",
    ],
    fanbase: "Gallop Nation",
  },
  {
    name: "Eagle Crest FC",
    image: "team-d",
    id: "6",
    attack: 88,
    defense: 85,
    foundingYear: 1975,
    colors: ["gold", "black"],
    colorCodes: ["#ffd700", "#000000"],
    achievements: [
      "Consistent Playoff Appearances",
      "Strong Aerial Attack Strategy",
      "Established in 1975",
    ],
    fanbase: "Eagle Squadron",
  },
];
